version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    groups:
      production-minor-patch:
        dependency-type: production
        update-types: [minor, patch]
      development-minor-patch:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Karachi
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /apps/platform-api
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: Asia/Karachi
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /apps/dashboard-web
    schedule:
      interval: weekly
      day: monday
      time: "10:15"
      timezone: Asia/Karachi
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /infrastructure/aws
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: Asia/Karachi
    open-pull-requests-limit: 3
