import type { Camera, HealthMetric, InspectionEvent } from './types';

export const cameras: Camera[] = [
  {
    id: 'CAM-01',
    name: 'Camera 01',
    zone: 'Bale Entry',
    status: 'online',
    aiStatus: 'processing',
    lastFrame: '2 sec ago',
    fps: 18,
    streamQuality: '1080p',
    todayEvents: 36,
  },
  {
    id: 'CAM-02',
    name: 'Camera 02',
    zone: 'Inspection Bay A',
    status: 'online',
    aiStatus: 'processing',
    lastFrame: '1 sec ago',
    fps: 20,
    streamQuality: '1080p',
    todayEvents: 42,
  },
  {
    id: 'CAM-03',
    name: 'Camera 03',
    zone: 'Inspection Bay B',
    status: 'warning',
    aiStatus: 'degraded',
    lastFrame: '18 sec ago',
    fps: 9,
    streamQuality: '720p',
    todayEvents: 31,
  },
  {
    id: 'CAM-04',
    name: 'Camera 04',
    zone: 'Bale Exit',
    status: 'online',
    aiStatus: 'processing',
    lastFrame: '3 sec ago',
    fps: 18,
    streamQuality: '1080p',
    todayEvents: 38,
  },
];

export const initialEvents: InspectionEvent[] = [
  {
    id: 'EVT-2407-0147',
    cameraId: 'CAM-02',
    cameraName: 'Camera 02',
    timestamp: '2026-07-24T11:42:16+05:00',
    outcome: 'missed',
    reason: 'Required inspection interaction not observed',
    confidence: 94,
    reviewStatus: 'unreviewed',
    summary: 'Bale exited the inspection zone without the required checking sequence being detected.',
    evidenceAvailable: true,
    modelVersion: 'cv-poc-0.3.0',
    ruleVersion: 'sop-draft-0.2',
    steps: [
      { label: 'Bale entered inspection zone', state: 'complete', time: '11:41:38' },
      { label: 'Worker interaction observed', state: 'failed' },
      { label: 'Required check completed', state: 'failed' },
      { label: 'Bale exited inspection zone', state: 'complete', time: '11:42:16' },
    ],
  },
  {
    id: 'EVT-2407-0146',
    cameraId: 'CAM-04',
    cameraName: 'Camera 04',
    timestamp: '2026-07-24T11:38:03+05:00',
    outcome: 'completed',
    reason: 'Inspection sequence completed',
    confidence: 97,
    reviewStatus: 'confirmed',
    summary: 'The required bale inspection interaction was completed before the bale left the monitored zone.',
    evidenceAvailable: true,
    remarks: 'Sequence reviewed and confirmed.',
    modelVersion: 'cv-poc-0.3.0',
    ruleVersion: 'sop-draft-0.2',
    steps: [
      { label: 'Bale entered inspection zone', state: 'complete', time: '11:37:21' },
      { label: 'Worker interaction observed', state: 'complete', time: '11:37:34' },
      { label: 'Required check completed', state: 'complete', time: '11:37:51' },
      { label: 'Bale exited inspection zone', state: 'complete', time: '11:38:03' },
    ],
  },
  {
    id: 'EVT-2407-0145',
    cameraId: 'CAM-03',
    cameraName: 'Camera 03',
    timestamp: '2026-07-24T11:31:44+05:00',
    outcome: 'unresolved',
    reason: 'Visibility insufficient for a reliable outcome',
    confidence: 62,
    reviewStatus: 'unreviewed',
    summary: 'Occlusion prevented the system from determining whether the required checking step was completed.',
    evidenceAvailable: true,
    modelVersion: 'cv-poc-0.3.0',
    ruleVersion: 'sop-draft-0.2',
    steps: [
      { label: 'Bale entered inspection zone', state: 'complete', time: '11:30:55' },
      { label: 'Worker interaction observed', state: 'unknown' },
      { label: 'Required check completed', state: 'unknown' },
      { label: 'Bale exited inspection zone', state: 'complete', time: '11:31:44' },
    ],
  },
  {
    id: 'EVT-2407-0144',
    cameraId: 'CAM-01',
    cameraName: 'Camera 01',
    timestamp: '2026-07-24T11:24:09+05:00',
    outcome: 'incomplete',
    reason: 'Inspection duration below threshold',
    confidence: 89,
    reviewStatus: 'confirmed',
    summary: 'Worker interaction was observed, but the required duration and sequence were not completed.',
    evidenceAvailable: true,
    remarks: 'Confirmed during supervisor review.',
    modelVersion: 'cv-poc-0.3.0',
    ruleVersion: 'sop-draft-0.2',
    steps: [
      { label: 'Bale entered inspection zone', state: 'complete', time: '11:23:33' },
      { label: 'Worker interaction observed', state: 'complete', time: '11:23:47' },
      { label: 'Required check completed', state: 'failed' },
      { label: 'Bale exited inspection zone', state: 'complete', time: '11:24:09' },
    ],
  },
  {
    id: 'EVT-2407-0143',
    cameraId: 'CAM-02',
    cameraName: 'Camera 02',
    timestamp: '2026-07-24T11:18:28+05:00',
    outcome: 'completed',
    reason: 'Inspection sequence completed',
    confidence: 96,
    reviewStatus: 'dismissed',
    summary: 'Automated result was dismissed during demo review to demonstrate the human-review workflow.',
    evidenceAvailable: false,
    remarks: 'Evidence unavailable in demo dataset.',
    modelVersion: 'cv-poc-0.3.0',
    ruleVersion: 'sop-draft-0.2',
    steps: [
      { label: 'Bale entered inspection zone', state: 'complete', time: '11:17:43' },
      { label: 'Worker interaction observed', state: 'complete', time: '11:17:58' },
      { label: 'Required check completed', state: 'complete', time: '11:18:17' },
      { label: 'Bale exited inspection zone', state: 'complete', time: '11:18:28' },
    ],
  },
];

export const healthMetrics: HealthMetric[] = [
  { id: 'edge', label: 'Local edge system', value: 'Online', detail: 'All core services are responding', state: 'healthy' },
  { id: 'ai', label: 'AI inference engine', value: 'Active', detail: '3 healthy streams, 1 degraded', state: 'warning' },
  { id: 'gpu', label: 'GPU utilization', value: '64%', detail: 'Temperature 68°C · Memory 7.2 / 12 GB', state: 'healthy' },
  { id: 'db', label: 'Local database', value: 'Healthy', detail: 'Last write less than 1 minute ago', state: 'healthy' },
  { id: 'storage', label: 'Evidence storage', value: '71% free', detail: '214 GB available on local volume', state: 'healthy' },
  { id: 'azure', label: 'Azure synchronization', value: 'Not configured', detail: 'Local PoC remains fully operational', state: 'neutral' },
];
