ALTER TABLE "cameras"
  ADD COLUMN IF NOT EXISTS "enabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "orientation" VARCHAR(64) NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS "expectedResolution" VARCHAR(64) NOT NULL DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS "expectedFps" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "statusSequence" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "source" VARCHAR(32) NOT NULL DEFAULT 'seed';

CREATE INDEX IF NOT EXISTS "cameras_enabled_status_idx"
  ON "cameras"("enabled", "status");
