import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { api, ApiError, runtime } from '../api';
import { certificationApi } from '../api/certification';
import { useAuth } from '../auth';
import { AppShell, ErrorState, Icon, LoadingPanel, StatusPill, outcomeTone, reviewTone, useToast } from '../components';
import { useMutation, useQuery, useQueryClient } from '../query';
import { Link, setNavigationBlocker } from '../router';
import type { ReviewEventInput, ReviewStatus } from '../types';
import { formatDateTime } from '../utils';

export default function EventDetailPage({ eventId }: { eventId: string }) {
  const { session, can } = useAuth(); const token = session?.token ?? ''; const queryClient = useQueryClient(); const { pushToast } = useToast();
  const eventQuery = useQuery({ key: `event:${eventId}`, enabled: Boolean(session && eventId), staleTime: 10_000, queryFn: (signal) => api.getEvent(token, eventId, signal) });
  const evidenceQuery = useQuery({ key: `event-evidence:${eventId}`, enabled: Boolean(session && eventId && runtime.dataMode === 'live'), staleTime: 10_000, queryFn: (signal) => certificationApi.getEvidence(token, eventId, signal) });
  const auditQuery = useQuery({ key: `event-audit:${eventId}`, enabled: Boolean(session && eventId && runtime.dataMode === 'live'), staleTime: 5_000, queryFn: (signal) => certificationApi.getAudit(token, eventId, signal) });
  const [reviewStatus, setReviewStatus] = useState<ReviewStatus>('unreviewed'); const [remarks, setRemarks] = useState(''); const event = eventQuery.data; const canReview = can('supervisor', 'admin');
  useEffect(() => { if (!event) return; setReviewStatus(event.reviewStatus); setRemarks(event.remarks ?? ''); }, [event]);
  useEffect(() => certificationApi.subscribe((type) => {
    if (type === 'inspection-event') { queryClient.invalidateQueries(`event:${eventId}`); queryClient.invalidateQueries('events:'); queryClient.invalidateQueries('summary'); }
    if (type === 'evidence-update') queryClient.invalidateQueries(`event-evidence:${eventId}`);
  }), [eventId, queryClient]);
  const dirty = useMemo(() => event ? event.reviewStatus !== reviewStatus || (event.remarks ?? '') !== remarks : false, [event, remarks, reviewStatus]);
  useEffect(() => {
    if (!dirty) return;
    const clearBlocker = setNavigationBlocker(() => 'You have unsaved review changes. Leave this event without saving?');
    const beforeUnload = (browserEvent: BeforeUnloadEvent) => { browserEvent.preventDefault(); browserEvent.returnValue = ''; };
    window.addEventListener('beforeunload', beforeUnload);
    return () => { clearBlocker(); window.removeEventListener('beforeunload', beforeUnload); };
  }, [dirty]);
  const mutation = useMutation<ReviewEventInput, NonNullable<typeof event>>(async (input, signal) => api.reviewEvent(token, eventId, input, signal));
  async function saveReview(formEvent: FormEvent<HTMLFormElement>) {
    formEvent.preventDefault(); if (!event || !canReview || mutation.isPending || reviewStatus === 'unreviewed') return;
    try { const updated = await mutation.mutate({ reviewStatus, remarks: remarks.trim(), expectedVersion: event.version }); queryClient.setQueryData(`event:${eventId}`, updated); queryClient.invalidateQueries('events:'); queryClient.invalidateQueries('summary'); queryClient.invalidateQueries(`event-audit:${eventId}`); pushToast('Review saved successfully.', 'good'); }
    catch (error) { if (error instanceof ApiError && error.code === 'VERSION_CONFLICT') pushToast('This event changed elsewhere. Refresh before saving again.', 'bad'); else pushToast(error instanceof Error ? error.message : 'Review could not be saved.', 'bad'); }
  }
  const evidence = evidenceQuery.data; const evidenceUrl = evidence ? certificationApi.evidenceUrl(evidence) : null;
  return <AppShell title="Event Detail">
    <div className="detail-back-row"><Link className="back-link" to="/events"><Icon name="back" size={18}/> Back to events</Link>{event && <span>Record version {event.version}</span>}</div>
    {eventQuery.isLoading && <LoadingPanel rows={10} label="Loading event detail"/>}{eventQuery.error !== undefined && !event && <ErrorState error={eventQuery.error} onRetry={() => void eventQuery.refetch()}/>} 
    {event && <><section className="event-detail-header"><div><span className="eyebrow">{event.cameraName} · {event.zone}</span><h2 tabIndex={-1}>{event.id}</h2><p>{formatDateTime(event.timestamp)}</p></div><div className="event-detail-header__status"><StatusPill label={event.outcome} tone={outcomeTone(event.outcome)}/><StatusPill label={event.reviewStatus} tone={reviewTone(event.reviewStatus)}/></div></section>
      <section className="event-detail-grid"><article className="panel evidence-panel"><div className="panel__header"><div><span className="eyebrow">Evidence</span><h3>Inspection snapshot and clip</h3></div></div>
        {evidenceQuery.isLoading && <LoadingPanel rows={4} label="Loading protected evidence"/>}
        {evidenceUrl && evidence?.state === 'available' && evidence.type === 'snapshot' && <div className="evidence-viewer"><img className="evidence-media" src={evidenceUrl} alt={`Protected inspection evidence for ${event.id}`}/><div className="evidence-toolbar"><span><Icon name="camera" size={18}/> {evidence.source} · {evidence.sizeBytes ?? 0} bytes</span><a className="button button--secondary" href={evidenceUrl} target="_blank" rel="noreferrer">Open evidence</a></div></div>}
        {evidenceUrl && evidence?.state === 'available' && evidence.type === 'clip' && <div className="evidence-viewer"><video className="evidence-media" controls preload="metadata" src={evidenceUrl}>Your browser cannot play this evidence clip.</video><div className="evidence-toolbar"><span><Icon name="camera" size={18}/> Protected clip · {evidence.durationMs ?? 0} ms</span></div></div>}
        {!evidenceQuery.isLoading && runtime.dataMode === 'mock' && event.evidenceAvailable && <div className="evidence-viewer" aria-label="Synthetic evidence preview"><div className="camera-scene camera-scene--evidence"><div className="camera-scene__grid"/><div className="conveyor"/><div className="bale bale--one"><span>BALE</span></div><div className="worker worker--one"><span/></div><div className="tracking-box tracking-box--bale"><span>Bale {event.confidence / 100}</span></div><span className="camera-id-overlay">{event.cameraId}</span><span className="camera-mode-overlay">MOCK EVIDENCE</span></div><div className="evidence-toolbar"><span><Icon name="camera" size={18}/> Synthetic preview only</span></div></div>}
        {!evidenceQuery.isLoading && (!event.evidenceAvailable || (runtime.dataMode === 'live' && (!evidence || evidence.state !== 'available'))) && <div className="evidence-unavailable"><Icon name="warning" size={30}/><h4>Evidence {evidence?.state ?? 'unavailable'}</h4><p>The event metadata remains reviewable. Evidence is delivered only through the protected API when its lifecycle state is available.</p></div>}
      </article>
      <article className="panel"><div className="panel__header"><div><span className="eyebrow">AI assessment</span><h3>Outcome details</h3></div></div><dl className="detail-list"><div><dt>Outcome</dt><dd><StatusPill label={event.outcome} tone={outcomeTone(event.outcome)}/></dd></div><div><dt>Reason</dt><dd>{event.reason}</dd></div><div><dt>Confidence</dt><dd>{event.confidence}%</dd></div><div><dt>Model version</dt><dd>{event.modelVersion}</dd></div><div><dt>Rule version</dt><dd>{event.ruleVersion}</dd></div></dl><p className="detail-summary">{event.summary}</p></article>
      <article className="panel sequence-panel"><div className="panel__header"><div><span className="eyebrow">Observed workflow</span><h3>Inspection sequence</h3></div></div><ol className="sequence-list">{event.steps.map((step) => <li key={step.label} className={`sequence-step sequence-step--${step.state}`}><span className="sequence-step__icon"><Icon name={step.state === 'complete' ? 'check' : step.state === 'failed' ? 'close' : 'warning'} size={18}/></span><div><strong>{step.label}</strong><span>{step.time ?? (step.state === 'unknown' ? 'Not determined' : 'Not observed')}</span></div></li>)}</ol></article>
      <article className="panel review-panel"><div className="panel__header"><div><span className="eyebrow">Human review</span><h3>Supervisor decision</h3></div></div><form onSubmit={(formEvent) => void saveReview(formEvent)}><fieldset disabled={!canReview || mutation.isPending}><legend>Review status</legend>{reviewStatus === 'unreviewed' && <p className="review-prompt">Select a supervisor decision to complete this review.</p>}<label className="radio-card"><input type="radio" name="review-status" value="confirmed" checked={reviewStatus === 'confirmed'} onChange={() => setReviewStatus('confirmed')}/><span><strong>Confirm</strong><small>Accept the automated outcome.</small></span></label><label className="radio-card"><input type="radio" name="review-status" value="dismissed" checked={reviewStatus === 'dismissed'} onChange={() => setReviewStatus('dismissed')}/><span><strong>Dismiss</strong><small>Mark the automated outcome as not applicable or incorrect.</small></span></label><label htmlFor="remarks">Supervisor remarks</label><textarea id="remarks" value={remarks} onChange={(inputEvent) => setRemarks(inputEvent.target.value)} maxLength={1000} rows={5} placeholder="Add review context or corrective notes"/><div className="character-count">{remarks.length}/1000</div></fieldset>{!canReview && <p className="permission-note"><Icon name="lock" size={18}/> Your role can view events but cannot change review status.</p>}{mutation.error !== undefined && <p className="form-error" role="alert">{mutation.error instanceof Error ? mutation.error.message : 'Review could not be saved.'}</p>}<div className="review-actions"><button className="button button--primary" type="submit" disabled={!canReview || !dirty || reviewStatus === 'unreviewed' || mutation.isPending}>{mutation.isPending ? 'Saving…' : 'Save review'}</button>{dirty && <span className="unsaved-label">Unsaved changes</span>}</div>{event.reviewedBy && <p className="review-audit">Last reviewed by {event.reviewedBy}{event.reviewedAt ? ` on ${formatDateTime(event.reviewedAt)}` : ''}.</p>}</form></article>
      <article className="panel"><div className="panel__header"><div><span className="eyebrow">Audit trail</span><h3>Recorded review history</h3></div></div>{auditQuery.isLoading && <LoadingPanel rows={3} label="Loading audit history"/>}{auditQuery.data?.length ? <ol className="sequence-list">{auditQuery.data.map((record) => <li key={record.id} className="sequence-step sequence-step--complete"><span className="sequence-step__icon"><Icon name="check" size={18}/></span><div><strong>{record.action}</strong><span>{record.actorDisplayName} · {formatDateTime(record.occurredAt)} · {record.correlationId}</span></div></li>)}</ol> : !auditQuery.isLoading && <p className="detail-summary">No review mutation has been recorded for this event.</p>}</article>
      </section></>}
  </AppShell>;
}
